name: paginate_firestore
description: A flutter package to simplify pagination with firestore data.
version: 1.0.3+1
homepage: https://github.com/excogitatr/paginate_firestore
issue_tracker: https://github.com/excogitatr/paginate_firestore/issues

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  cloud_firestore: ^5.6.4
  provider: ^6.1.2
  firebase_core: ^3.12.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
